[theme]
primaryColor = "#38bdf8"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1e29"
textColor = "#f3f4f6"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
